### ISSUE TITLE
Can't install using pip

### ISSUE THREAD

**Issue by virajbpatel** [matthiasprobst/synpivimage#2]
I'm having trouble installing with pip, when I run `pip install synpivimage` it returns
```
ERROR: Could not find a version that satisfies the requirement synpivimage (from versions: none)
ERROR: No matching distribution found for synpivimage
```
I have also had trouble with installing `pivmetalib` in the same way. I cloned both repositories in an attempt to install them through GitHub but I now receive the following error locating metadata for the library:

```
Exception has occurred: PackageNotFoundError
No package metadata was found for pivmetalib
StopIteration: 

During handling of the above exception, another exception occurred:

  File "C:\Users\vbp24\Documents\PhD\Synthetic PIV Pipeline\pivmetalib\_version.py", line 6, in <module>
    __version__ = _version('pivmetalib')
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vbp24\Documents\PhD\Synthetic PIV Pipeline\pivmetalib\__init__.py", line 6, in <module>
    from ._version import __version__
  File "C:\Users\vbp24\Documents\PhD\Synthetic PIV Pipeline\synpivimage\io.py", line 12, in <module>
    from pivmetalib.pivmeta import LaserModel, DigitalCameraModel
  File "C:\Users\vbp24\Documents\PhD\Synthetic PIV Pipeline\synpivimage\__init__.py", line 7, in <module>
    from .io import Imwriter, HDF5Writer
  File "C:\Users\vbp24\Documents\PhD\Synthetic PIV Pipeline\synthetic_piv_trial.py", line 2, in <module>
    import synpivimage as spi
importlib.metadata.PackageNotFoundError: No package metadata was found for pivmetalib
```
I'm not very familiar with how Python packages can be installed outside of PIP so I may have messed up during the installation. How can I fix this?

**Comment by matthiasprobst** [comment]
Please let me know which version you are using. I will try to elaborate on your problem later today.

**Comment by matthiasprobst** [comment]
@virajbpatel Please make sure you are using `python>=3.8`. I have fixed some things. So please pull the latest commit from the main branch again. Happy to help again if problems persist.

**Comment by virajbpatel** [comment]
I'm using Python 3.12.6. The library is now working for me after cloning the GitHub repository, thank you.
